version: '3.5'
services:
  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=builder
      - MYSQL_USER=builder
      - MYSQL_PASSWORD=admin
    expose:
      - 3306
    networks:
      - builder
  backend:
    build: .
    depends_on:
      - mysql
    ports:
      - 8080:8080
    networks:
      - builder
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=builder
      - DATABASE_NAME=builder
      - DATABASE_PASSWORD=admin
      - DATABASE_PORT=3306
networks:
  builder:
    driver: bridge